# Generated by Django 6.1.1 on 2026-09-20 11:51

import common.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PERSONAL', 'Personal'), ('ESCROW', 'Escrow (System)'), ('REVENUE', 'Platform Revenue')], db_index=True, default='PERSONAL', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('balance', models.PositiveBigIntegerField(default=0)),
                ('card_number', common.models.EncryptedCharField(blank=True, max_length=512, null=True)),
                ('card_number_hmac', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('shaba_number', common.models.EncryptedCharField(blank=True, max_length=512, null=True)),
                ('account_number', common.models.EncryptedCharField(blank=True, max_length=512, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField()),
                ('balance_before', models.PositiveBigIntegerField(blank=True, null=True)),
                ('balance_after', models.PositiveBigIntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('SYSTEM_PAYMENT', 'System Payment'), ('REFUND', 'Refund')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed')], max_length=20)),
                ('transaction_group_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.wallet')),
            ],
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='wallet_balance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(fields=('user', 'type'), name='unique_user_wallet_type', nulls_distinct=False),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', 'created_at'], name='finance_wal_wallet__e9aa50_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['transaction_group_id'], name='finance_wal_transac_904dc4_idx'),
        ),
    ]
